# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test Slack Notification
on:
  workflow_dispatch:
    description: "Manually trigger Slack notification test"

jobs:
  send-slack-message:
    name: Send structured data to Slack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          payload-file-path: "./slack-test-payload.json"
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
