name: "Test Slack Integration"

on:
  workflow_dispatch:
    description: "Test Slack notification integration"

jobs:
  test-slack:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: "Install dependencies"
        run: pnpm install

      - name: "Run translation script (dry run)"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_ACTIONS: "true"
          DRY_RUN: "true"
          SLACK_OUTPUT_FILE: "slack-payload.json"
        run: pnpm run translate

      - name: "Display GitHub environment variables"
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"  
          echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
          echo "Expected commit URL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"

      - name: "Display generated payload"
        run: |
          if [ -f slack-payload.json ]; then
            echo "Generated Slack payload:"
            cat slack-payload.json
          else
            echo "No Slack payload file found"
            exit 1
          fi

      - name: "Read Slack payload"
        id: slack
        run: |
          if [ -f slack-payload.json ]; then
            echo "payload=$(cat slack-payload.json)" >> $GITHUB_OUTPUT
            echo "payload-exists=true" >> $GITHUB_OUTPUT
          else
            echo "payload-exists=false" >> $GITHUB_OUTPUT
          fi

      - name: "Send Slack notification"
        if: steps.slack.outputs.payload-exists == 'true'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          payload: ${{ steps.slack.outputs.payload }}
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
